# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menumodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='about_you',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
