# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menumodel_about_you'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
