# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menumodel_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='menumodel',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
