# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menumodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menumodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
